# Generated by Django 2.2.5 on 2019-09-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristicNum', models.IntegerField(default=0)),
                ('animalType', models.CharField(max_length=100)),
                ('animalColor', models.CharField(max_length=20)),
                ('animalSex', models.CharField(max_length=1)),
                ('animalAge', models.CharField(max_length=5)),
                ('animalWeight', models.CharField(max_length=10)),
                ('timeAdded', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('ownerId', models.UUIDField(primary_key=True, serialize=False)),
                ('farmNumber', models.UUIDField()),
                ('farmAddress', models.CharField(max_length=200)),
                ('farmCity', models.CharField(max_length=200)),
                ('farmState', models.CharField(max_length=200)),
                ('timeAdded', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='FarmOwner',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('timeAdded', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalsOwned',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('animalName', models.CharField(max_length=200)),
                ('characteristic', models.IntegerField(default=0)),
                ('timeAdded', models.DateTimeField(verbose_name='date added')),
                ('farmNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.FarmLocation')),
                ('ownderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.FarmOwner')),
            ],
        ),
    ]
