# Generated by Django 2.2.5 on 2019-11-11 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='ownderId',
            new_name='ownerId',
        ),
        migrations.RemoveField(
            model_name='farmowner',
            name='id',
        ),
        migrations.AddField(
            model_name='farmowner',
            name='userId',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animalcharacteristics',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='farmlocation',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='farmowner',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
