# Generated by Django 2.2.5 on 2019-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191111_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmowner',
            name='userId',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
