# Generated by Django 2.2.5 on 2019-11-11 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20191111_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmowner',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
