# Generated by Django 2.2.5 on 2019-11-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20191111_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmowner',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
