# Generated by Django 2.2.5 on 2019-11-21 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20191111_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmowner',
            name='animalPictureFileType',
        ),
        migrations.AddField(
            model_name='animal',
            name='animalPictureFileType',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
