# Generated by Django 2.2.5 on 2019-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20191122_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animalPictureFileType',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AddField(
            model_name='animal',
            name='animalId',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='animalcharacteristics',
            name='animal',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='homepage.Animal'),
            preserve_default=False,
        ),
    ]
