# Generated by Django 2.2.5 on 2019-11-24 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20191122_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animalName',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='animalcharacteristics',
            name='characteristicNum',
        ),
        migrations.AddField(
            model_name='animalcharacteristics',
            name='animalName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalcharacteristics',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
