# Generated by Django 2.2.5 on 2019-11-24 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20191123_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='ownerId',
            new_name='farmOwner',
        ),
        migrations.AddField(
            model_name='animal',
            name='animalAge',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='animalColor',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='animalName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='animalSex',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='animalType',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='animalWeight',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='thumb',
            field=models.ImageField(blank=True, default='homepage/static/homepage/images/no-image-available.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='AnimalCharacteristics',
        ),
    ]
