# Generated by Django 2.2.5 on 2019-11-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20191124_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='farmOwner',
        ),
    ]
