# Generated by Django 2.2.5 on 2019-11-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_animal_farmowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalSex',
            field=models.CharField(max_length=10),
        ),
    ]
