# Generated by Django 2.2.5 on 2019-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20191126_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='thumb',
            field=models.ImageField(blank=True, default='homepage/static/homepage/images/no-image-available.png', upload_to='media/images'),
        ),
    ]
