# Generated by Django 2.2.5 on 2019-11-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20191126_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='thumb',
            field=models.ImageField(blank=True, default='media/images/no-image-available.png', upload_to='media/images'),
        ),
    ]
