# Generated by Django 2.2.5 on 2019-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20191126_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='thumb',
            field=models.ImageField(blank=True, default='media/media/no-image-available.jpeg', upload_to='media'),
        ),
    ]
