# Generated by Django 2.2.5 on 2019-12-05 00:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20191204_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default='media/media/no-image-available.jpg', upload_to='media/'),
        ),
    ]
